"use client";

import { useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";
import { maskPhoneNumber, sanitizePhoneNumber, validateFinalAnswer } from "../src/utils/game";

type Screen = "title" | "intro" | "game" | "ending" | "credits";
type Direction = "front" | "right" | "back" | "left";
type Room = { id:number; era:string; title:string; year:string; letter:string; item:string; icon:string; palette:string; objects:string[]; puzzle:string; clue:string; solution:string; label:string; memory:string[]; note:string; hints:string[] };

const rooms: Room[] = [
  {id:1,era:"영유아기",title:"아주 작은 나의 방",year:"1998",letter:"기",item:"모빌의 별",icon:"✦",palette:"nursery",objects:["커다란 곰 인형","가족사진","흔들의자","천장 모빌"],puzzle:"새벽의 숫자",clue:"곰의 단추 · 사진 속 사람 · 모빌의 별",solution:"337",label:"세 자리 숫자",memory:["나는 이 밤을 기억하지 못한다.","엄마는 내가 조용히 숨 쉬는 걸 확인하고서야 잠들었다."],note:"새벽 3시 37분. 오늘도 많이 울었지만 우유를 먹고 잠들었다.",hints:["방 안에서 셀 수 있는 것들을 찾아보자.","곰, 사진, 별의 순서다.","정답은 337이다."]},
  {id:2,era:"어린이집",title:"비 오는 날의 교실",year:"2003",letter:"억",item:"네잎클로버",icon:"♧",palette:"classroom",objects:["원아수첩","비 오는 창문","장난감 주방","도시락"],puzzle:"오늘의 도시락",clue:"원아수첩 속 그림 순서를 따라 반찬을 적자",solution:"김달걀당근멸치",label:"반찬 네 가지",memory:["나는 엄마가 늦게 왔다고 기억했다.","하지만 엄마는 내가 나오기 전부터 기다리고 있었다."],note:"오늘도 씩씩하게 다녀오자.",hints:["수첩의 답글에 좋아하는 반찬이 있다.","김부터 시작해 보자.","김, 달걀, 당근, 멸치 순서다."]},
  {id:3,era:"사춘기",title:"닫힌 문 앞",year:"2011",letter:"하",item:"숟가락",icon:"⌇",palette:"hallway",objects:["굳게 닫힌 방문","식어 가는 미역국","찌그러진 케이크","주방시계"],puzzle:"반복해서 데운 국",clue:"전자레인지에 남은 마지막 시각을 맞추자",solution:"2130",label:"네 자리 시각",memory:["나는 엄마가 나를 내버려두었다고 생각했다.","엄마는 내가 열어주지 않는 문 앞에서 기다리고 있었다."],note:"화를 내고 문을 닫았지만 배가 고프면 나오겠지. 국이 너무 짜지 않았으면 좋겠다.",hints:["기록된 시각은 점점 늦어진다.","마지막으로 데운 시간을 보자.","정답은 2130이다."]},
  {id:4,era:"대학 입시",title:"불 꺼지지 않는 책상",year:"2016",letter:"지",item:"낡은 손목시계",icon:"◷",palette:"study",objects:["빽빽한 문제집","꺼진 휴대전화","합격 발표 화면","멈춘 손목시계"],puzzle:"전송되지 않은 시간",clue:"휴대전화의 마지막 메시지 시각",solution:"1147",label:"네 자리 시각",memory:["그날 나는 내 노력이 결실을 맺었다고 생각했다.","그 노력 뒤에 누군가의 포기가 있었다는 건 몰랐다."],note:"결과가 어떻든 괜찮아. 엄마한테는 네가 제일 중요해. — 전송되지 않음, 11:47",hints:["꺼진 휴대전화에 충전기를 연결해 보자.","전송되지 않은 메시지의 시각이다.","정답은 1147이다."]},
  {id:5,era:"현재",title:"내 방이 사라진 본가",year:"오늘",letter:"",item:"성장일기",icon:"▤",palette:"home",objects:["벽의 키 자국","바닥의 책상 자국","문 뒤 스티커","천장의 야광별"],puzzle:"다섯 번째 서랍",clue:"네 개의 물건에서 드러난 글자를 이어 보자",solution:"기억하지",label:"일기의 빈칸",memory:["나는 사랑을 찾기 위해 다섯 개의 방을 지나왔다.","하지만 그 사랑은 서랍 속에 숨겨져 있던 것이 아니었다."],note:"네가 ______ 못해도 우리는 네 모든 날을 기억한다.",hints:["지금까지 얻은 글자를 살펴보자.","기 · 억 · 하 · 지를 이어 보자.","정답은 기억하지다."]},
];

type Store={room:number;completed:number[];inventory:string[];hints:Record<number,number>;sound:boolean;neutral:boolean;finished:boolean;setRoom:(n:number)=>void;complete:(r:Room)=>void;hint:(n:number)=>void;toggleSound:()=>void;setNeutral:(v:boolean)=>void;finish:()=>void;reset:()=>void};
const useGame=create<Store>()(persist((set)=>({room:1,completed:[],inventory:[],hints:{},sound:true,neutral:false,finished:false,setRoom:(room)=>set({room}),complete:(r)=>set(s=>({completed:s.completed.includes(r.id)?s.completed:[...s.completed,r.id],inventory:s.inventory.includes(r.item)?s.inventory:[...s.inventory,r.item]})),hint:(n)=>set(s=>({hints:{...s.hints,[n]:Math.min((s.hints[n]??0)+1,3)}})),toggleSound:()=>set(s=>({sound:!s.sound})),setNeutral:(neutral)=>set({neutral}),finish:()=>set({finished:true}),reset:()=>set({room:1,completed:[],inventory:[],hints:{},finished:false})}),{name:"fifth-drawer-save",storage:createJSONStorage(()=>localStorage),partialize:({room,completed,inventory,hints,sound,neutral,finished})=>({room,completed,inventory,hints,sound,neutral,finished})}));

function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>e.key==="Escape"&&close();window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[close]);
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" onClick={close} aria-label="닫기">×</button><p className="eyebrow">기억의 조각</p><h2 id="modal-title">{title}</h2>{children}</section></div>
}

function Title({go}:{go:(s:Screen)=>void}){
 const {completed,neutral,setNeutral,reset}=useGame();const [notice,setNotice]=useState(false);
 return <main className="title-screen"><div className="title-copy"><p className="overline">A QUIET POINT & CLICK MYSTERY</p><h1><span>다섯 번째</span> 서랍</h1><p className="subtitle">The Fifth Drawer</p><div className="rule"/><p className="title-quote">네 개의 서랍은 닫혀 있었다.<br/>다섯 번째만 빼고.</p></div><div className="drawer-menu" aria-label="주 메뉴">
  <button onClick={()=>{reset();setNotice(true)}}><b>01</b><span>새 게임<small>처음부터 기억을 따라갑니다</small></span><i>→</i></button>
  <button disabled={!completed.length} onClick={()=>go("game")}><b>02</b><span>이어하기<small>{completed.length?`${completed.length}개의 기억을 찾았습니다`:"저장된 기억이 없습니다"}</small></span><i>→</i></button>
  <button onClick={()=>setNeutral(!neutral)}><b>03</b><span>호칭 설정<small>{neutral?"소중한 사람":"엄마"}로 표현합니다</small></span><i>{neutral?"중립":"기본"}</i></button>
  <button onClick={()=>go("credits")}><b>04</b><span>크레딧<small>이 이야기를 만든 마음들</small></span><i>→</i></button>
 </div><p className="title-foot">작은 소리와 희미한 흔적을 천천히 살펴보세요.</p>{notice&&<Modal title="어디에도 맞지 않는 열쇠" close={()=>setNotice(false)}><p className="large-copy">오래된 서랍에서 작은 열쇠 하나를 발견했다.<br/>무엇을 여는 열쇠인지는 알 수 없다.</p><p className="paper-note">불을 끄고, 서두르지 말고, 방 안의 흔적을 따라가세요.</p><button className="primary" onClick={()=>go("intro")}>열쇠를 집어 든다 <span>→</span></button></Modal>}</main>
}

function Intro({go}:{go:(s:Screen)=>void}){const[step,setStep]=useState(0);const lines=["오랜만에 부모님의 집을 찾았다.","내가 사용하던 방은 이미 사라지고 없었다.","엄마는 서랍을 정리하다 발견했다며 작은 열쇠 하나를 내게 건넸다.","“이게 네 방에 있던 건데, 어디 열쇠인지는 모르겠다.”"];return <main className="prologue"><div className="clock" aria-hidden="true"><span>XI</span><i/><b>VI</b></div><div className={`ghost-door ${step>=3?"visible":""}`}/><section className="dialogue" aria-live="polite" onClick={()=>step<3?setStep(step+1):go("game")}><p className="eyebrow">{step===3?"엄마":"나"}</p><p>{lines[step]}</p><span>{step===3?"문 열기":"계속"} ↘</span></section></main>}

function Game({go}:{go:(s:Screen)=>void}){
 const store=useGame(),room=rooms[store.room-1];const[direction,setDirection]=useState<Direction>("front"),[modal,setModal]=useState<"inspect"|"puzzle"|"hint"|"memory"|null>(null),[selected,setSelected]=useState(room.objects[0]),[answer,setAnswer]=useState(""),[error,setError]=useState("");const solved=store.completed.includes(room.id),dirs:Direction[]=["front","right","back","left"],idx=dirs.indexOf(direction),level=store.hints[room.id]??0;
 const submit=()=>{const ok=room.id===5?validateFinalAnswer(answer):answer.replace(/\s/g,"")===room.solution;if(!ok)return setError("아직 열리지 않는다. 단서를 다시 천천히 살펴보자.");store.complete(room);setError("");setModal("memory")};
 const advance=()=>{setModal(null);setAnswer("");if(room.id===5){store.finish();go("ending")}else{store.setRoom(room.id+1);setDirection("front")}};
 return <main className="game-shell"><header className="game-header"><div><p>다섯 번째 서랍</p><span>The Fifth Drawer</span></div><div className="chapter"><span>기억 {String(room.id).padStart(2,"0")}</span><strong>{room.era}</strong></div><nav><button onClick={()=>setModal("hint")}>힌트 <em>{level}/3</em></button><button onClick={store.toggleSound} aria-label={store.sound?"소리 끄기":"소리 켜기"}>{store.sound?"♪":"♩"}</button><button onClick={()=>go("title")} aria-label="메뉴">☰</button></nav></header>
 <section className={`scene ${room.palette} view-${direction}`}><div className="scene-wash"/><div className="year-stamp">{room.year}</div><div className="room-art" aria-hidden="true"><div className="window"><i/><i/><i/></div><div className="cabinet"><span/><span/><span/><span/><span/></div><div className="furniture"/><div className="lamp"/>{room.id===1&&<div className="mobile">☾ · ✦ · ☁ · ᨒ</div>}{room.id===3&&<div className="closed-door"><small>밥은 먹어.</small></div>}{room.id===5&&<div className="stars">✦　·　✦　·</div>}</div>
 {room.objects.map((o,i)=><button key={o} className={`hotspot hotspot-${i}`} aria-label={`${o} 조사하기`} onClick={()=>{setSelected(o);setModal(i===3?"puzzle":"inspect")}}><span>{i+1}</span><b>{o}</b></button>)}<button className="turn left" onClick={()=>setDirection(dirs[(idx+3)%4])} aria-label="왼쪽 방향 보기">‹</button><button className="turn right" onClick={()=>setDirection(dirs[(idx+1)%4])} aria-label="오른쪽 방향 보기">›</button><div className="direction-label"><span>◌</span> {direction==="front"?"정면":direction==="right"?"오른쪽":direction==="back"?"뒤쪽":"왼쪽"}</div></section>
 <footer className="game-footer"><section className="inventory" aria-label="인벤토리"><p>기억의 물건 <span>{store.inventory.length}/5</span></p><div>{[0,1,2,3,4].map(slot=>{const item=rooms.find(r=>r.item===store.inventory[slot]);return <button key={slot} disabled={!item} aria-label={item?.item??`빈 칸 ${slot+1}`}>{item?<><i>{item.icon}</i><small>{item.item}</small></>:<b>{slot+1}</b>}</button>})}</div></section><section className="inner-voice" aria-live="polite"><p>{solved?"기억이 되돌아왔다.":room.id===3?"이 문은 열 수 없다. 누군가의 마음은 억지로 열 수 없으니까.":"익숙한데, 아주 오래된 꿈속 같다."}</p><span>{room.title}</span></section></footer>
 {modal==="inspect"&&<Modal title={selected} close={()=>setModal(null)}><div className="object-symbol">{room.icon}</div><p className="large-copy">{selected==="굳게 닫힌 방문"?"이 문은 열 수 없다. 누군가의 마음은 억지로 열 수 없으니까.":room.clue}</p><p className="paper-note">{room.note}</p><button className="primary" onClick={()=>setModal("puzzle")}>퍼즐 살펴보기 <span>→</span></button></Modal>}
 {modal==="puzzle"&&<Modal title={room.puzzle} close={()=>setModal(null)}><p className="large-copy">{room.clue}</p>{room.id===5&&<div className="letter-row">{["기","억","하","지"].map(l=><i key={l}>{l}</i>)}</div>}<label className="answer-field">{room.label}<input autoFocus value={answer} maxLength={20} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="정답을 입력하세요"/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" onClick={submit}>서랍 열기 <span>→</span></button></Modal>}
 {modal==="hint"&&<Modal title={`힌트 ${Math.max(1,level)}/3`} close={()=>setModal(null)}><p className="large-copy">{room.hints[Math.max(0,level-1)]}</p><button className="primary" onClick={()=>store.hint(room.id)}>{level>=3?"마지막 힌트입니다":"조금 더 알려주세요"} <span>＋</span></button></Modal>}
 {modal==="memory"&&<Modal title={`${room.item}을(를) 찾았다`} close={advance}><div className="found-item">{room.icon}</div>{room.memory.map(line=><p className="memory-line" key={line}>{line}</p>)}{room.letter&&<div className="found-letter"><span>되찾은 글자</span><b>{room.letter}</b></div>}<button className="primary" onClick={advance}>{room.id===5?"마지막 페이지 넘기기":"다음 기억으로"} <span>→</span></button></Modal>}</main>
}

function Ending({go}:{go:(s:Screen)=>void}){
 const{neutral}=useGame();const[mode,setMode]=useState<"choice"|"phone"|"letter"|"drawers">("choice"),[phone,setPhone]=useState(""),[name,setName]=useState(""),[letter,setLetter]=useState(""),[show,setShow]=useState(false);const clean=sanitizePhoneNumber(phone),canCall=clean.replace(/\D/g,"").length>=7;
 const pick=async()=>{const nav=navigator as Navigator&{contacts?:{select:(p:string[],o:{multiple:boolean})=>Promise<{name?:string[];tel?:string[]}[]>}};if(!nav.contacts?.select)return setMode("phone");try{const c=(await nav.contacts.select(["name","tel"],{multiple:false}))[0];if(c?.tel?.[0]){setPhone(c.tel[0]);setName(c.name?.[0]??"선택한 사람");setMode("phone")}}catch{setMode("phone")}};
 const download=()=>{const blob=new Blob([letter],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="다섯번째서랍_마음의편지.txt";a.click();URL.revokeObjectURL(url)};
 if(mode==="drawers")return <main className="final-screen"><div className="ending-drawers" aria-label="다섯 개의 서랍이 닫힙니다">{rooms.map((r,i)=><div key={r.id} style={{animationDelay:`${i*.35}s`}}><span>{r.icon}</span><b>{r.item}</b></div>)}</div><p className="overline">THE FIFTH DRAWER</p><h1>다섯 번째 서랍은<br/><em>아직 끝나지 않은</em> 우리의 이야기다.</h1><p>사랑은 기억 속에만 남는 것이 아니라<br/>오늘 다시 전할 수 있는 마음이다.</p><button className="primary" onClick={()=>go("credits")}>크레딧 보기 <span>→</span></button></main>;
 return <main className="ending-screen"><section className="ending-copy"><p className="overline">마지막 기억</p><h1>지금 떠오르는<br/><em>사람이 있나요?</em></h1><p>마음은 나중으로 미룰수록<br/>전하기 어려워질지도 모릅니다.</p><blockquote>“{neutral?"언제든지 돌아와도 돼.":"언제든지 돌아와도 돼. 엄마는 늘 여기 있을게."}”</blockquote></section><section className="contact-card">
 {mode==="choice"&&<><p>엄마가 아니어도 괜찮아요.<br/>지금 마음을 전하고 싶은 사람에게 연락해보세요.</p><button className="call-button" onClick={pick}><span>☎</span><b>{neutral?"소중한 사람에게 전화 걸기":"엄마에게 전화 걸기"}</b><i>연락처에서 직접 선택합니다 →</i></button><button className="soft-button" onClick={()=>setMode("letter")}>마음속으로 편지 남기기</button><button className="text-button" onClick={()=>setMode("drawers")}>통화하지 않고 엔딩 보기</button><button className="text-button" onClick={()=>go("game")}>조금 더 머물기</button></>}
 {mode==="phone"&&<><p className="eyebrow">선택한 사람에게 전화를 걸까요?</p><h2>{name||"전화번호 직접 입력"}</h2><label className="answer-field">전화번호<input value={phone} inputMode="tel" autoComplete="tel" onChange={e=>setPhone(e.target.value)} placeholder="010-0000-0000"/></label>{canCall&&<><p className="masked">{show?clean:maskPhoneNumber(clean)} <button onClick={()=>setShow(!show)}>{show?"번호 숨기기":"번호 보기"}</button></p><div className="qr"><QRCodeSVG value={`tel:${clean}`} size={132}/><span>휴대전화 카메라로<br/>QR 코드를 스캔해주세요</span></div></>}<a className={`primary ${!canCall?"disabled":""}`} href={canCall?`tel:${clean}`:undefined}>전화 걸기 <span>→</span></a><button className="text-button" onClick={()=>setMode("choice")}>이전으로</button></>}
 {mode==="letter"&&<><p className="eyebrow">마음속 편지</p><h2>전하지 못했던 말을<br/>이곳에 적어보세요.</h2><textarea value={letter} maxLength={500} onChange={e=>setLetter(e.target.value)} placeholder="천천히, 마음이 가는 만큼…"/><div className="letter-meta"><span>새로고침하면 사라집니다</span><b>{letter.length} / 500</b></div><p>전해지지 못한 마음도 사라지는 것은 아닙니다.</p><button className="primary" disabled={!letter} onClick={download}>내 편지 내려받기 <span>↓</span></button><button className="text-button" onClick={()=>setMode("drawers")}>편지를 마음에 두고 엔딩 보기</button></>}</section></main>
}

function Credits({go}:{go:(s:Screen)=>void}){return <main className="credits"><p className="overline">THE FIFTH DRAWER</p><h1>다섯 번째 서랍</h1><p>기획 · 디자인 · 개발<br/>당신의 기억을 오래 바라본 사람들</p><div className="credit-rule"/><blockquote>네가 기억하지 못하는 순간에도<br/>누군가는 언제나 너를 사랑하고 있었다.</blockquote><button className="primary" onClick={()=>go("title")}>처음으로 <span>↙</span></button></main>}

export default function Page(){const[screen,setScreen]=useState<Screen>("title"),store=useGame();const complete=store.complete,reset=store.reset;useEffect(()=>{if(new URLSearchParams(location.search).get("debug")==="true")(window as Window&{gameDebug?:unknown}).gameDebug={unlockAll:()=>rooms.forEach(complete),ending:()=>setScreen("ending"),reset}},[complete,reset]);return screen==="title"?<Title go={setScreen}/>:screen==="intro"?<Intro go={setScreen}/>:screen==="game"?<Game go={setScreen}/>:screen==="ending"?<Ending go={setScreen}/>:<Credits go={setScreen}/>}
